### ISSUE TITLE
Ruby Capstone

### ISSUE THREAD

**Issue by kessie2862** [kessie2862/Catalog-of-my-things#30]
## How many members at the project?
> The number of members of this project is 3 members: 💯

- [ ] The first one is @kessie2862 he is the person responsible for the **`Team Member#1`** task 
- [ ] The second one is @mailsg he is the person responsible for the **`Team Member#2`** task 
- [ ] The third one is @ANTOINE1128 he is the person responsible for the **`Team Member#3`** task 

## Here is the link to the Kanban board 
- [ ] Just click [here](https://github.com/kessie2862/Catalog-of-my-things/projects/1) to see the kanban board and check our cards in detail😊

**Comment by Whoistolu** [comment]
### Hi Team,
@kessie2862 , @mailsg and @ANTOINE1128 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

### Highlight
🔆 Cards on the board have descriptions and number of points
🔆 Tasks are distributed in a fair way
🔆 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
